name: Deploy Portfolio

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 185.98.137.247
          username: deploy
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/portfolio

            echo "🚀 Starting deployment..."
            //display vps_password
            echo "🔐 Using password: ${{ secrets.VPS_PASSWORD }}"

            echo "🔄 Pull latest code..."
            git fetch origin master
            git reset --hard origin/master
            git clean -fd

            echo "📦 Backend install..."
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            echo "🧹 Clear Laravel cache..."
            php artisan optimize:clear

            echo "🎨 Frontend build..."
            npm ci
            npm run build

            echo "⚡ Re-cache Laravel..."
            php artisan optimize
